### PR TITLE
Add the sponsor badge in the Footer

### PR DESCRIPTION
**Pull request by AdelZhrr**
Work done for the Sponsor badge issue.

### CODE REVIEW

**Comment by guhur** [comment]
Right now, the badge sounds like: "Mieux Voter belongs to HelloAsso", and not "Hey, you can help us with a donation through HelloAsso". 

@oceanBigOne what do you think? What would you recommend??

**Comment by oceanBigOne** [comment]
Ok, why not... but please add `target="_blank"` to avoid the user loses what he typed.

We can also add a button (simple bootstrap button) on the home page (under the sentence `Pas de publicité et pas de cookie publicitaire.` ). 

What do you think ?

**Comment by AdelZhrr** [comment]
I think it's better to leave it in the Footer. Like this, the link is present in all pages of the website and not only in the home page.

We can also make something like "Cette nouvelle façon de voter vous a plu ? Devenez adhérant à Mieux Voter ! Plus de détail en cliquant ici." in the result page.

Good idea ?

**Comment by oceanBigOne** [comment]
I wasn't clear. I was thinking of adding the link on the home page. I also think we should leave it in the footer.

It's a good idea to put it on the result page, but it's better to make a graphic insert (not just a simple link)

**Comment by AdelZhrr** [comment]
Ok I understand for the home page and I can do it.

But I don't understand what do you mean by "better to make a graphic insert".

**Comment by AdelZhrr** [comment]
The result after all changes 
Capture d’écran 2020-01-18 à 21 51 06
Capture d’écran 2020-01-18 à 21 46 36

**Comment by oceanBigOne** [comment]
Sorry, but it's not good for me. I can't explain with details but the layout is not correct (button too large, text stick to the field ...)

**Comment by AdelZhrr** [comment]
Is that better ? @guhur 
Capture d’écran 2020-01-19 à 13 25 49
Capture d’écran 2020-01-19 à 13 25 34

**Comment by oceanBigOne** [comment]
Hello, here are some banner (gif and png) to test if it is better ..
[Banner-helloAsso.zip](https://github.com/MieuxVoter/mvfront-react/files/4082947/Banner-helloAsso.zip)
.

**Comment by guhur** [comment]
Solved by https://github.com/MieuxVoter/mvfront-react/pull/24

**Pull request closed without merging**
